### ISSUE TITLE
Vector class can be used wrongly

### ISSUE THREAD

**Issue by hasher-hasher** [hasher-hasher/TinyEngine#37]
The methods up, down, left and right inside Vector class should return just a double-sized vector. It should be possible just to use Vector.up, not Vector.up.position.

**Comment by alexandrebarbaruiva** [comment]
@hasher-hasher `invalid` tag is for issues that are deemed `not a real issue` (not valid) by us when someone else submits a bug. An example is when someone reports a bug but it's actually their machine not having Python.
